### ISSUE TITLE
Init Callbacks Have Empty Attributes/Data

### ISSUE THREAD

**Issue by Zamiell** [Meowlala/RepentanceAPIIssueTracker#20]
In most (or all?) init callbacks, many attributes are not initialized.

For example, in the MC_POST_EFFECT_INIT callback, the following attributes are either set to 0 or nil:
- Position
- SpawnerType
- SpawnerVariant
- MaxDistance

And possibly others - I have not performed an exhaustive test.

This is a problem because for many mod use-cases, it makes the init callback useless, since you generally only want your code to apply to specific things, and not all things.

As a toy example, say that you wanted to have an item that modified creep that spawned within a certain radius of the player.  For this, the obvious implementation would be to use `entity:GetData()` to mark eligible creep with a custom attribute in the MC_POST_EFFECT_INIT callback. However, since you can't access the position, this won't work.

As a workaround, mods are forced to check for the existence of new things on every frame in the POST_UPDATE callback, which (obviously) is not ideal.

**Comment by UnderscoreKilburn** [comment]
This will be partially fixed in the next patch, Position, Velocity, SpawnerType, SpawnerVariant and SpawnerEntity are now set before PostInit callbacks are called. Other attributes (i.e. effect attributes or tear flags) will not be set, there's no good way around this that doesn't require rewriting a ton of existing game code. In those cases you can hook into MC_POST_TEAR_UPDATE or MC_POST_EFFECT_UPDATE and check those attributes on the first frame (this is how the game internally does it for most entities that have extra attributes that need to be checked upon spawning).

**Comment by Meowlala** [comment]
Verified to be fixed as Kil described in repentance's first API patch.
