### ISSUE TITLE
AddCollectibleEffect crashes the game

### ISSUE THREAD

**Issue by pedroff1** [Meowlala/RepentanceAPIIssueTracker#257]
AddCollectibleEffect crashes the game when called, depending of the `CollectibleId` value used

Example code:

```lua  local my_mod = RegisterMod( "sample_mod", 1 )

local function post_player_init(mod,player)
	player:GetEffects():AddCollectibleEffect(1,false)
end

my_mod:AddCallback( ModCallbacks.MC_POST_PLAYER_INIT, post_player_init )
```

How to reproduce on the debug console:
1) Run the following line:
` lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(1,false)`

Notes: 
- `CollectibleId` 5 (My Reflectrion) does not crash when used. Neither does 3 (Spoon Bender) (Thanks @Somdudewilson for pointing it out)
Example code: `lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(5)`

**Comment by Somdudewillson** [comment]
> AddCollectibleEffect crashes the game whenever called, regardless of its arguments.

This is untrue.
Example: If you call `lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(3)`

**Comment by pedroff1** [comment]
> 
> 
> > AddCollectibleEffect crashes the game whenever called, regardless of its arguments.
> 
> This is untrue.
> Example: If you call `lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(3)`

Counterexample provided had syntax error that resulted in the function not being called (missing argument in `Isaac.GetPlayer()` ).
Upon correction (resulting in the command `lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(3)` ), the command line also crashes the game, as expected

**Comment by Somdudewillson** [comment]
> > > AddCollectibleEffect crashes the game whenever called, regardless of its arguments.
> > 
> > 
> > This is untrue.
> > Example: If you call `lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(3)`
> 
> Counterexample provided had syntax error that resulted in the function not being called (missing argument in `Isaac.GetPlayer()` ).
> Upon correction (resulting in the command `lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(3)` ), the command line also crashes the game, as expected

If you try to provide invalid syntax to the `lua` command it throws an error, as you would expect.
It throws no such error if you call `Isaac.GetPlayer()` with no arguments.

This is because the numerical argument in `Isaac.GetPlayer()` is optional, as stated by the docs.

Furthermore, if my counter-example didn't run, how, exactly, would it apply the psychic tear effect as it does?
And, while `CollectibleType.COLLECTIBLE_SPOON_BENDER` behaves somewhat strangely, `CollectibleType.COLLECTIBLE_MY_REFLECTION` operates perfectly.
`lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(5)`,
`lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(5,true)`,
`lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(5,false)`,
`lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(5)`,
`lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(5,true)`, and
`lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(5,false)`
all operate exactly as expected.

**Comment by pedroff1** [comment]
> 
> 
> > > > AddCollectibleEffect crashes the game whenever called, regardless of its arguments.
> > > 
> > > 
> > > This is untrue.
> > > Example: If you call `lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(3)`
> > 
> > 
> > Counterexample provided had syntax error that resulted in the function not being called (missing argument in `Isaac.GetPlayer()` ).
> > Upon correction (resulting in the command `lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(3)` ), the command line also crashes the game, as expected
> 
> If you try to provide invalid syntax to the `lua` command it throws an error, as you would expect.
> It throws no such error if you call `Isaac.GetPlayer()` with no arguments.
> 
> This is because the numerical argument in `Isaac.GetPlayer()` is optional, as stated by the docs.
> 
> Furthermore, if my counter-example didn't run, how, exactly, would it apply the psychic tear effect as it does?
> And, while `CollectibleType.COLLECTIBLE_SPOON_BENDER` behaves somewhat strangely, `CollectibleType.COLLECTIBLE_MY_REFLECTION` operates perfectly.
> `lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(5)`,
> `lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(5,true)`,
> `lua Isaac.GetPlayer():GetEffects():AddCollectibleEffect(5,false)`,
> `lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(5)`,
> `lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(5,true)`, and
> `lua Isaac.GetPlayer(0):GetEffects():AddCollectibleEffect(5,false)`
> all operate exactly as expected.

Holy hell, that's true!
Sorry for the misunderstanding

I still find some values for it cause crashes, but the examples cited do indeed work

**Comment by Gemboat** [comment]
Reading all this inspired me to test it out myself, and then inspired me to report on my findings here.
It is in my professional opinion that this function is haunted.

Sometimes it crashes, sometimes it does not. Sometimes it gets into a bad mood and starts crashing consistently -- these moods persist over game restarts (obviously), but fade in a few minutes if let alone. All the examples in the above posts have worked for me; they have also all crashed the game for me on other occasions. A command can succeed when run in the console, and then crash the game when run again without closing the console to unpause the game.
I've been able to notice a few patterns (hallucinated or otherwise) -- running the command while transitioning between rooms crashes much more frequently. Running the command while the below callback is active crashes much more frequently. Feel free to test this out.
```lua
Mod = RegisterMod("Test",1)
function Mod:Report() print(Isaac.GetFrameCount()) end
Mod:AddCallback(ModCallbacks.MC_POST_RENDER,Mod.Report)
```
But the obvious method works too; run whatever AddCollectibleEffect you want in the console, and then repeat Up-Enter-Up-Enter until the game crashes. One time it took me 80 repetitions of that to get the crash, but it's never failed. (don't try to shortcut with a loop or `repeat 50`; this doesn't seem to increase the rate of it crashing)

I have no idea what conclusion to draw from this. Regardless, it's certainly not robust enough to consider using in a real mod, so this definitely is a broken function.

**Comment by Meowlala** [comment]
Fixed (for the provided functions, at least) in 1.7.5.
