### ISSUE TITLE
An EntityPlayer method to summon a Book of Virtues wisp without using your active

### ISSUE THREAD

**Issue by AgentCucco** [Meowlala/RepentanceAPIIssueTracker#55]
I have a few mod ideas in mind, and one of them involves generating a Wisp based off your current Active Item without actually giving you a free active use,, so I was just thinking of a simple new method like:

EntityPlayer.AddWisps(_int_ Count, _int_ CollectibleType, _boolean_ Passive)
- **Count**: Defines the amount of wisps you will get.
- **CollectibleType**: Used to determine the Wisp type you get depending on the active. Any items without a wisp attached to them will spawn a normal base Wisp.
- **Passive**: Used to determine if the Wisp should instead be a Passive Item wisp from Tainted Bethany.

**Comment by jsgnextortex** [comment]
This can already be done by spawning the wisp, you set the collectible type using the subtype of the wisp. Same about the alt bethany ones too.

**Comment by Meowlala** [comment]
A function like this could still be helpful to directly associate the wisp with the player that's getting it, perhaps? Not sure whether this should be closed or not.

**Comment by jsgnextortex** [comment]
In that case, an AddFamiliar function would be the ideal rather than a function to specifically add wisps tho.

**Comment by Meowlala** [comment]
Well, it wouldn't really be much different from adding blue flies. The current `EntityPlayer:AddFamiliar` is a weird one, since it has to be used in the familiar cache evaluation and is practically unusable for base game familiars due to being a "set count" rather than "add / subtract", on top of not supporting subtypes. Maybe that could use an issue of its own?

**Comment by jsgnextortex** [comment]
It would be better than the one that adds blue flies even, but Im not defending the blue flies one since that one also seems pointless to me, lol.
Fixing the current AddFamiliar function so it works outside of the cacheeval callback and is, overall, less of a pain in the ass to use would completley outclass both the wisps function and the blue flies one. Overall, I think having a small amount of usefull functions that allow us to do several things is better than having a bazillion specific functions that only do one specific thing and it's just the same thing that other function does but slightly better, but I guess its subjective.

**Comment by Meowlala** [comment]
Both item wisps and active wisps are addable in the first repentance API patch, using `EntityPlayer:AddWisp` and `EntityPlayer:AddItemWisp`, which I have verified to work.
