### ISSUE TITLE
[REP+] GridEntity:Destroy() is broken

### ISSUE THREAD

**Issue by jerbmega** [Meowlala/RepentanceAPIIssueTracker#568]
GridEntity:Destroy() errors with (EntityRef expected, got string)

**Comment by NAT0P0TAT0** [comment]
also Room:DestroyGrid(), I got mods that had either error to work by just adding EntityRef(player) as a parameter
e.g. GridEntity:Destroy(true, EntityRef(player))

I'm assuming these and the kill() function were updated so you could specify what did the killing/breaking, but if that's the case it'd be good to have a default placeholder value when the ref parameter is missing instead of breaking

**Comment by epfly6** [comment]
Fixed in v1.9.7.7
